### ISSUE TITLE
API Secret and Key in public file

### ISSUE THREAD

**Issue by SpaceApe1** [IgorWounds/Stocktwits-AMC-Algotrading101#1]
Hi Igor,

Great Work and thank you fore sharing your code and ideas!

Is it intended, that your API keys and secrets are public in this file?
https://github.com/IgorWounds/Stocktwits-AMC-Algotrading101/blob/main/Stocktwits.ipynb

I would like to get in contact with you. You can write me under Twitter @SpaceApeOne.
What is your most successful strategy so far, you can share? ;)

Regards from Germany
Kai

**Comment by IgorWounds** [comment]
Hi Kai,

Thank you most kindly!

Yes, I usually tend to leave the API keys written for test accounts so that the readers of the article don't need to go through the sign-up process and can get straight into the coding part to get a feel for the product.

Sure, I'll write to you soon.

Kind regards,
Igor
